name: drift_db_viewer_example
description: A new Flutter application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  drift: ^2.0.1
  drift_db_viewer:
    path: ../
  flutter:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.9
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
